<a href="https://colab.research.google.com/github/skawns0724/Machine-Learning/blob/main/1_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
score = [[15 ,16, 17],
         [25, 26, 27],
         [35, 36, 37]]

In [2]:
type(score)

list

In [3]:
import numpy as np

In [4]:
np_score = np.array(score)

In [6]:
type(np_score)

numpy.ndarray

In [7]:
import pandas as pd

In [8]:
df_score = pd.DataFrame(np_score, index=['A_class', 'B_class', 'C_class'], columns=['kor', 'eng', 'math'])

In [9]:
df_score

kor  eng  math
A_class   15   16    17
B_class   25   26    27
C_class   35   36    37

In [12]:
avg_kor = df_score['kor'].mean()

In [13]:
avg_kor

25.0

In [16]:
max_kor = df_score['kor'].max()

In [17]:
max_kor

35

In [18]:
new_np_array = df_score.values

In [19]:
new_np_array

array([[15, 16, 17],
       [25, 26, 27],
       [35, 36, 37]])

In [21]:
new_list_score = new_np_array.tolist()

In [22]:
new_list_score

[[15, 16, 17], [25, 26, 27], [35, 36, 37]]

In [23]:
practice = [[13,135,18,156],
            [255,1856,163,135],
            [156,322,456,132],
            [345,621,1111,351]]

In [31]:
practice_array = np.array(practice)

In [32]:
practice_array

array([[  13,  135,   18,  156],
       [ 255, 1856,  163,  135],
       [ 156,  322,  456,  132],
       [ 345,  621, 1111,  351]])

In [33]:
practice_df = pd.DataFrame(practice_array, index=['강남', '강북', '강동', '강서'], columns=['고도', '위도', '위치', '위상'])

In [34]:
practice_df

고도    위도    위치   위상
강남   13   135    18  156
강북  255  1856   163  135
강동  156   322   456  132
강서  345   621  1111  351

In [35]:
new_practice_array = practice_df.values

In [36]:
new_practice_array

array([[  13,  135,   18,  156],
       [ 255, 1856,  163,  135],
       [ 156,  322,  456,  132],
       [ 345,  621, 1111,  351]])

In [39]:
new_practice_list = new_practice_array.tolist()

In [40]:
new_practice_list

[[13, 135, 18, 156],
 [255, 1856, 163, 135],
 [156, 322, 456, 132],
 [345, 621, 1111, 351]]